// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJu9pRhFqDoaCmIFc6JCOYuy6CalEyc3Q',
    appId: '1:31612694618:web:f5401978d2bc4be262e863',
    messagingSenderId: '31612694618',
    projectId: 'devmob-apvpedagogie',
    authDomain: 'devmob-apvpedagogie.firebaseapp.com',
    storageBucket: 'devmob-apvpedagogie.firebasestorage.app',
    measurementId: 'G-4JBYWNRX0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrz07DcI3BeeQ6PgykrJWHw8skVxPvjEY',
    appId: '1:31612694618:android:00f44c5433660a0562e863',
    messagingSenderId: '31612694618',
    projectId: 'devmob-apvpedagogie',
    storageBucket: 'devmob-apvpedagogie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyMhCGgP3zEAv7niYXIBcagdaOR3CSrvc',
    appId: '1:31612694618:ios:bafdd7d0364cc47b62e863',
    messagingSenderId: '31612694618',
    projectId: 'devmob-apvpedagogie',
    storageBucket: 'devmob-apvpedagogie.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyMhCGgP3zEAv7niYXIBcagdaOR3CSrvc',
    appId: '1:31612694618:ios:bafdd7d0364cc47b62e863',
    messagingSenderId: '31612694618',
    projectId: 'devmob-apvpedagogie',
    storageBucket: 'devmob-apvpedagogie.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJu9pRhFqDoaCmIFc6JCOYuy6CalEyc3Q',
    appId: '1:31612694618:web:17b5a2b702903e9b62e863',
    messagingSenderId: '31612694618',
    projectId: 'devmob-apvpedagogie',
    authDomain: 'devmob-apvpedagogie.firebaseapp.com',
    storageBucket: 'devmob-apvpedagogie.firebasestorage.app',
    measurementId: 'G-3NNQ7K4EQ2',
  );
}
